### ISSUE TITLE
Request Member Attributes not functioning

### ISSUE THREAD

**Issue by eddieholeman** [ShepherdDev/self-join#1]
When I set the Request Member Attributes block setting to "None" and visit the sign-up online, the person is added to the group as expected.  We have used this block for months with no issue. But, when I change the Request Member Attributes block setting to "Required" or "All" and then sign-up online, the member attribute shows, and I fill in the requested attribute information (text field) and click Submit. the confirmation screen does not show the group name after "You have been added to the following groups:"     The person is not added to the group.

**Comment by cabal95** [comment]
Fixed in https://github.com/ShepherdDev/self-join/commit/e7009fa8d4748a6409812540b76c0ae79d9e83fd.
