### ISSUE TITLE
Self-join error in v9.1

### ISSUE THREAD

**Issue by eddieholeman** [ShepherdDev/self-join#2]
We have upgrading our sandbox to Rock v9.1. When we attempt to load a page which has the self-join block on the page, we see the following error:

`Error Loading Block: Self Join Show Details
c:\inetpub\wwwroot\Plugins\com_shepherdchurch\SelfJoin\SelfJoin.ascx.cs(516): error CS0619: 'Rock.Model.Workflow.Activate(Rock.Model.WorkflowType, string, Rock.Data.RockContext)' is obsolete: 'For improved performance, use the Activate method that takes a WorkflowTypeCache parameter instead. IMPORTANT NOTE: When using the new method, the Workflow object that is returned by that method will not have the WorkflowType property set. If you are referencing the WorkflowType property on a Workflow returned by that method, you will get a Null Reference Exception! You should use the new WorkflowTypeCache property on the workflow instead.'`

Is this a known issue? Are you still keeping self-join going? We love it and would love to not lose it if possible. Thanks.

**Comment by cabal95** [comment]
It looks like I fixed this last year but never pushed the code. Was probably going to test it that weekend and then forgot to go back and push the code to github.

If you download the SelfJoin.ascx and SelfJoin.ascx.cs files again it should have the fix now.

**Comment by eddieholeman** [comment]
Thanks Daniel. That fixed the issue.
